version: '3.8'
services:
  db:
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    image: postgres:14.5
    networks:
      - backend
  task-manager:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - backend
volumes:
  postgres_data:
networks:
  backend:
    driver: bridge